# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1464, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree.setGeometry(QtCore.QRect(10, 10, 351, 481))
        self.tree.setAutoExpandDelay(-1)
        self.tree.setObjectName("tree")
        self.tree.headerItem().setText(0, "请选择目标文件夹...")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 500, 351, 311))
        self.textEdit.setObjectName("textEdit")
        self.btn_yeild = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yeild.setGeometry(QtCore.QRect(370, 10, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.btn_yeild.setFont(font)
        self.btn_yeild.setObjectName("btn_yeild")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 0, 911, 811))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 170, 161, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_report = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_report.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.comboBox_report.setObjectName("comboBox_report")
        self.comboBox_report.addItem("")
        self.comboBox_report.addItem("")
        self.comboBox_report.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 110, 161, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_chart = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_chart.setGeometry(QtCore.QRect(10, 20, 141, 22))
        self.comboBox_chart.setObjectName("comboBox_chart")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        self.comboBox_chart.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1464, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_yeild.setText(_translate("MainWindow", "Start"))
        self.groupBox.setTitle(_translate("MainWindow", "Table"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Report"))
        self.comboBox_report.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_report.setItemText(1, _translate("MainWindow", "VP"))
        self.comboBox_report.setItemText(2, _translate("MainWindow", "Normal"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Diagram"))
        self.comboBox_chart.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_chart.setItemText(1, _translate("MainWindow", "BoxPlots"))
        self.comboBox_chart.setItemText(2, _translate("MainWindow", "LineChart"))
        self.comboBox_chart.setItemText(3, _translate("MainWindow", "ScatterDiagram"))
        self.comboBox_chart.setItemText(4, _translate("MainWindow", "Histogram"))
        self.comboBox_chart.setItemText(5, _translate("MainWindow", "CurveChart"))
        self.comboBox_chart.setItemText(6, _translate("MainWindow", "NormalDistribution"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
